version: '3.9'

services:
  explorer:
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    restart: on-failure
    networks:
      - database
    ports:
      - "44333:80"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
    depends_on:
      - database
  encounters:
    image: encounters
    restart: on-failure
    networks:
      - database
    ports:
      - "81:81"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
    depends_on:
      - explorer
      - database
  tours:
    image: tours
    restart: on-failure
    networks:
      - database
    ports:
      - "88:88"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
    depends_on:
      - explorer
      - database
  database:
    image: postgres:13
    restart: always
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: explorer
    ports:
      - "5432:5432"
    volumes:       
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: init.sql
        target: /tmp/explorer-init.sql

volumes:
  database-data:
    name: explorer

networks:
  database:
    name: database
    driver: local