server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: encounters_logs
    static_configs:
      - targets: ['encounters:81']
        labels:
          job: encounters_logs
  - job_name: tours_logs
    static_configs:
      - targets: ['tours:88']
        labels:
          job: tours_logs
